### ISSUE TITLE
N51ICP_read_uid() and N51ICP_read_ucid() always get 0xff on Arduino UNO and MEGA2560

### ISSUE THREAD

**Issue by llinjupt** [nikitalita/NuMicro-8051-prog#1]
Hi nikitalita, 

First of all, thanks a lot for your awesome work.

After trying nuvo51icp on Arduino UNO and MEGA2560 with the target MCU N76E003A, I found that N51ICP_read_uid() and N51ICP_read_ucid() always got 0xff,  and at the same time N51ICP_read_device_id() and  N51ICP_read_cid() could got the correct values.

Later I tried Gregory McGarry's nuvoprog and got the same result. Since I don't have a Raspberry Pi 5 to cross-verify, would you like to confrim if it is only an issue on arduino? Thanks.

**Comment by nikitalita** [comment]
Might be timing issues. Those are pretty slow 8-bit MCUs, and I only tested the MEGA2560 briefly; as I recall, It was pretty finnicky, and there have been changes to the code since then that might have made it slow enough to not be viable on those. If it's an option for you, I recommend using something like a Pico, which is a lot faster and costs like 5 bucks.

**Comment by nikitalita** [comment]
My bad, I misread your comment. The UID and the UCID are not able to be read on the N76E003 through ICP; it apparently does work on some other 8051 chips, but not on the N76E003 or the others I have tested. All it does on the N76E003 is return the first few bytes of the program rom.

I should probably update the documentation stating that it doesn't work on those.

**Comment by llinjupt** [comment]
> My bad, I misread your comment. The UID and the UCID are not able to be read on the N76E003 through ICP; it apparently does work on some other 8051 chips, but not on the N76E003 or the others I have tested. All it does on the N76E003 is return the first few bytes of the program rom.

Accroding to the the datasheet, it should work through IAPCMD 0x04 to read 96-bit UID.  Unluckly I broke the N76E003 by setting the RPD in CONFIG0 accidently just now, and I am not sure if there is a way to reset the bit back.  Instead, I tried N76E885 with Gregory McGarry's nuvoprog on ESP8266 NODEMCU 1.0 (ESP-12E Module), and it worked. For both N76E885 and 003 are from the same family, it should also work with N76E003.

If you can give a try on Raspberry Pi 5 to cross-verify, it will help a lot.

**Comment by nikitalita** [comment]
> Accroding to the the datasheet, it should work through IAPCMD 0x04 to read 96-bit UID. Unluckly I broke the N76E003 by setting the RPD in CONFIG0 accidently just now, and I am not sure if there is a way to reset the bit back.

Oof, tough luck. It's a huge bitch to try and get it back into programming mode after that happens. I just solder another one after that happens.

> Instead, I tried N76E885 with Gregory McGarry's nuvoprog on ESP8266 NODEMCU 1.0 (ESP-12E Module), and it worked. For both N76E885 and 003 are from the same family, it should also work with N76E003.

You'd think so! But no. Even Nuvoton's official ICP software greys out the display the UID and UCID for the N76E003.

> If you can give a try on Raspberry Pi 5 to cross-verify, it will help a lot.

I don't have a N76E885 to test. I've tested the N76E003 countless times, trying different command opcodes experimentally, to get it to read out the UID and UCID, and nothing has worked. I've only been able to get it through IAP in the LDROM.

**Comment by llinjupt** [comment]
> Oof, tough luck. It's a huge bitch to try and get it back into programming mode after that happens. I just solder another one after that happens.

Yeah.

> Even Nuvoton's official ICP software greys out the display the UID and UCID for the N76E003.

It sounds really strange if the the datasheet tells the truth. Anyway I have booked some new N76E003 chips and after trying I will give feedback to confirm if its an issue and then you could close it. It might take one week I guess.

**Comment by nikitalita** [comment]
The datasheet is telling the truth about the IAP commands. It doesn't talk about the ICP protocol at all, it is undocumented and proprietary, and the IAP commands do not always correspond 1-to-1 with the ICP commands. For example, the ICP config read and write commands don't correspond with the IAP commands. I wouldn't be surprised if they just left out the microcode that handled UID/UCID reads from these chips.

**Comment by llinjupt** [comment]
@nikitalita Yeah, you'are right. I have just tested the new coming N76E003A and the result is coherent with what you said. 
After programming,  N76E003 returned the first few bytes of the program rom other than real UID.

And N76E885/616 all behave the same. Therefore it's clear that it's not a bug and you can colse it. Thanks again for your helpful information.
